/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Recordings": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Responses": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Resumes": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Sessions": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}